runtime: docker
docker:
  registry: docker.io
  namespace: vertisan
  name: pulselink-user-service
  main_service: user-svc-api
  shell: /bin/bash
modes:
  base: docker/docker-compose.yml
  dev: docker/docker-compose.yml docker/docker-compose.dev.yml
  test: docker/docker-compose.yml docker/docker-compose.test.yml
