version: "3.9"

services:

    user-svc-api:
        build:
            context: ../
            dockerfile: Dockerfile
            target: development
        env_file: ../.env
        environment:
            - APP_ENV=dev
            - APP_PORT=80
            - NODE_ENV=development
        ports:
            - "8030:80"
        volumes:
            - ../app:/var/www
            - ../docker/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
            - /var/www/node_modules
            - /var/www/.pnpm-store

    user-svc-db:
        image: postgres:14.9
        env_file: ../.env
        environment:
            PGDATA: /var/lib/postgresql/data/pgdata
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        volumes:
            - user-svc-db-data:/var/lib/postgresql/data/pgdata
        networks:
            - pulselink

    user-svc-db-browser:
        image: dbgate/dbgate:latest
        env_file: ../.env
        environment:
            CONNECTIONS: db
            LABEL_db: Postgres
            SERVER_db: ${DATABASE_HOST}
            USER_db: ${DATABASE_USER}
            PASSWORD_db: ${DATABASE_PASSWORD}
            PORT_db: ${DATABASE_PORT}
            ENGINE_db: postgres@dbgate-plugin-postgres
        ports:
            - "8031:3000"
        networks:
            - pulselink


volumes:
    user-svc-db-data: {}
